<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Order for continue Med    IV fluid  Bloo_35a3a7</name>
   <tag></tag>
   <elementGuidId>6b473a5a-3ede-427b-8037-08372822e75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ng-tns-c25-13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c25-13</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order for continue Med  เวชภัณฑ์  IV fluid  Blood  LAB  Diet  X-ray  Treatment  Service  Other Medวิธีใช้จำนวนรายละเอียดอื่นๆยาให้ทันที CancelSaveCancelประวัติข้อมูลยา×ทั้งหมดH/MOrder ยาเดิมไม่พบข้อมูลประวัติยาของคนไข้.Favorite×Favorite name Share favourite เฉพาะตัวเอง (Only me) แพทย์ทั้งหมด พยาบาล เภสัชกร บันทึกปิดFavorite×ค้นหาเลือกปิด(Lab list)×CancelSubmit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order&quot;)/ipd-detail[@class=&quot;ng-tns-c25-13&quot;]/div[@class=&quot;row ipd-order&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table tbl-fix-head tbl-ipd-order&quot;]/tbody[@class=&quot;ng-tns-c25-13 ng-star-inserted&quot;]/tr[@class=&quot;ng-tns-c25-13&quot;]/td[@class=&quot;ng-tns-c25-13&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order for continue'])[2]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order for one day'])[2]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Order for continue Med  เวชภัณฑ์  IV fluid  Blood  LAB  Diet  X-ray  Treatment  Service  Other Medวิธีใช้จำนวนรายละเอียดอื่นๆยาให้ทันที CancelSaveCancelประวัติข้อมูลยา×ทั้งหมดH/MOrder ยาเดิมไม่พบข้อมูลประวัติยาของคนไข้.Favorite×Favorite name Share favourite เฉพาะตัวเอง (Only me) แพทย์ทั้งหมด พยาบาล เภสัชกร บันทึกปิดFavorite×ค้นหาเลือกปิด(Lab list)×CancelSubmit' or . = 'Order for continue Med  เวชภัณฑ์  IV fluid  Blood  LAB  Diet  X-ray  Treatment  Service  Other Medวิธีใช้จำนวนรายละเอียดอื่นๆยาให้ทันที CancelSaveCancelประวัติข้อมูลยา×ทั้งหมดH/MOrder ยาเดิมไม่พบข้อมูลประวัติยาของคนไข้.Favorite×Favorite name Share favourite เฉพาะตัวเอง (Only me) แพทย์ทั้งหมด พยาบาล เภสัชกร บันทึกปิดFavorite×ค้นหาเลือกปิด(Lab list)×CancelSubmit')]</value>
   </webElementXpaths>
</WebElementEntity>
