<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_VS_ng-untouched ng-valid ui-inputt_f7c558</name>
   <tag></tag>
   <elementGuidId>3acf0e7c-0ce0-4e43-9c6e-ae2cd1d31602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/progression-note/div/div[3]/div[2]/div/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.ng-untouched.ng-valid.ui-inputtext.ui-corner-all.ui-inputtextarea-resizable.ui-state-default.ui-widget.ng-dirty.ui-state-filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoresize</name>
      <type>Main</type>
      <value>autoResize</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ui-inputtext ui-corner-all ui-inputtextarea-resizable ui-state-default ui-widget ng-dirty ui-state-filled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order&quot;)/ipd-detail[@class=&quot;ng-tns-c25-13&quot;]/div[@class=&quot;row ipd-order&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table tbl-fix-head tbl-ipd-order&quot;]/tbody[@class=&quot;ng-tns-c25-13 ng-star-inserted&quot;]/tr[@class=&quot;ng-tns-c25-13&quot;]/td[@class=&quot;ng-tns-c25-13&quot;]/progression-note[@class=&quot;ng-tns-c25-13&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;add-list-box&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-10&quot;]/div[@class=&quot;hm-form-input&quot;]/textarea[@class=&quot;ng-untouched ng-valid ui-inputtext ui-corner-all ui-inputtextarea-resizable ui-state-default ui-widget ng-dirty ui-state-filled&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/progression-note/div/div[3]/div[2]/div/div[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
   </webElementXpaths>
</WebElementEntity>
