<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Add_ng-valid ui-inputtext ui-corne_c4b75d</name>
   <tag></tag>
   <elementGuidId>3d9dbf03-8a4d-4fb6-9411-a641519335b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/progression-note/div/div[4]/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoresize</name>
      <type>Main</type>
      <value>autoResize</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ui-inputtext ui-corner-all ui-inputtextarea-resizable ui-state-default ui-widget ng-dirty ui-state-filled ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order&quot;)/ipd-detail[@class=&quot;ng-tns-c25-37&quot;]/div[@class=&quot;row ipd-order&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table tbl-fix-head tbl-ipd-order&quot;]/tbody[@class=&quot;ng-tns-c25-37 ng-star-inserted&quot;]/tr[@class=&quot;ng-tns-c25-37&quot;]/td[@class=&quot;ng-tns-c25-37&quot;]/progression-note[@class=&quot;ng-tns-c25-37&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;add-list-box&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-10&quot;]/div[@class=&quot;hm-form-input&quot;]/textarea[@class=&quot;ng-valid ui-inputtext ui-corner-all ui-inputtextarea-resizable ui-state-default ui-widget ng-dirty ui-state-filled ng-touched&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/progression-note/div/div[4]/div[2]/div/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/textarea</value>
   </webElementXpaths>
</WebElementEntity>
