<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Save_incomplete_shapes_canvas_whiteboard</name>
   <tag></tag>
   <elementGuidId>b891d255-414e-4be6-b78b-7b693a08680a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.incomplete_shapes_canvas_whiteboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='canvasModal_jeodt']/canvas-whiteboard/div/canvas[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>incomplete_shapes_canvas_whiteboard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1918</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>922</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canvasModal_jeodt&quot;)/canvas-whiteboard[1]/div[@class=&quot;canvas_wrapper_div&quot;]/canvas[@class=&quot;incomplete_shapes_canvas_whiteboard&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='canvasModal_jeodt']/canvas-whiteboard/div/canvas[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas[2]</value>
   </webElementXpaths>
</WebElementEntity>
