<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FBS_checkbox-checkmark</name>
   <tag></tag>
   <elementGuidId>3c8b8909-5ecf-4b44-96b1-5c8ac49f9a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/order/assessment-modal/div/div/div/div[2]/table/tbody/tr/td/form/dynamic-form/form-checkbox/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12 > label.checkbox-container > span.checkbox-checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-checkmark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order&quot;)/ipd-detail[@class=&quot;ng-tns-c25-10&quot;]/div[@class=&quot;row ipd-order&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table tbl-fix-head tbl-ipd-order&quot;]/tbody[@class=&quot;ng-tns-c25-10 ng-star-inserted&quot;]/tr[@class=&quot;ng-tns-c25-10&quot;]/td[@class=&quot;ng-tns-c25-10&quot;]/order[@class=&quot;ng-tns-c25-10 ng-star-inserted&quot;]/assessment-modal[1]/div[@class=&quot;modal fade in show&quot;]/div[@class=&quot;modal-dialog modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/table[1]/tbody[1]/tr[1]/td[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/dynamic-form[1]/form-checkbox[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row hm-form-layout-checkbox-level_1 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;col-12&quot;]/label[@class=&quot;checkbox-container&quot;]/span[@class=&quot;checkbox-checkmark&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order']/ipd-detail/div[2]/div/table/tbody/tr/td/order/assessment-modal/div/div/div/div[2]/table/tbody/tr/td/form/dynamic-form/form-checkbox/div/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form-checkbox/div/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
